---
title: "Titanic - Association Rules Mining "
output: html_notebook
---

## Load data
```{r}
library(arules)
library(arulesViz)

titanic = read.csv("train.csv", header = TRUE)
titanic<- data.frame(sapply(titanic,as.factor))
```

## Get rules
```{r}
rules <- apriori(titanic)
inspect(rules[1:20])
```

## Get rules -> Survived
```{r}
rules <- apriori(titanic,parameter=list(minlen=2, supp=0.005, conf=0.8),appearance=list(rhs=c("Survived=0", "Survived=1"),default="lhs"),control=list(verbose=F))
rules.sorted <- sort(rules, by="lift")
inspect(rules.sorted[1:20])
```

## Find redundant rules
```{r}
subset.matrix <- is.subset(rules.sorted, rules.sorted, sparse = FALSE)
subset.matrix[lower.tri(subset.matrix, diag=T)] <- NA
redundant <- colSums(subset.matrix, na.rm=T) >= 1
which(redundant[1:20])
```

## Remove redundant rules
```{r}
rules.pruned <- rules.sorted[!redundant]
inspect(rules.pruned[1:20])
```

## Rules - Plot
```{r}
plot(rules.pruned)
```

## Rules - Graph 10
```{r}

plot(rules.pruned[1:10], method="graph", control=list(type="items"))
```

## Rules - Graph 20
```{r}

plot(rules.pruned[1:20], method="graph", control=list(type="items"))
```

## Rules - Graph 50
```{r}

plot(rules.pruned[1:50], method="graph", control=list(type="items"))
```

## Rules - Graph 100
```{r}

plot(rules.pruned[1:100], method="graph", control=list(type="items"))
```

## Rules - Paracoord 10
```{r}
plot(rules.pruned[1:10], method="paracoord", control=list(reorder=TRUE))
```

## Rules - Paracoord 20
```{r}
plot(rules.pruned[1:20], method="paracoord", control=list(reorder=TRUE))
```

## Rules - Paracoord 50
```{r}
plot(rules.pruned[1:50], method="paracoord", control=list(reorder=TRUE))
```

