---
title: "Titanic - Analiza prin clasificare supervizata"
output: html_notebook
---

## Load and process data
```{r}
library(rattle)
library(rpart.plot)
library(RColorBrewer)
library(e1071)
library(class)
library(randomForest)
library(xgboost)
library(neuralnet)
library('dplyr')
library(caret)

train <- read.csv("../input_files/train.csv")
test <- read.csv("../input_files/test.csv")

full  <- bind_rows(train, test)

# Extract title from name
full$Title <- gsub('(.*, )|(\\..*)', '', full$Name)
rare_title <- c('Dona', 'Lady', 'the Countess','Capt', 'Col', 'Don', 
                'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer')
full$Title[full$Title == 'Mlle']        <- 'Miss' 
full$Title[full$Title == 'Ms']          <- 'Miss'
full$Title[full$Title == 'Mme']         <- 'Mrs' 
full$Title[full$Title %in% rare_title]  <- 'Rare Title'

# Create a family size variable including the passenger themselves
full$Fsize <- full$SibSp + full$Parch + 1

train <- full[1:891,]
test <- full[892:1309,]

# Remove Name, Ticket and Cabin columns
train <- train[,-c(4,9,11)]
test <- test[,-c(2,4,9,11)]

# Change Sex to 0 = male, 1 = female
train$Sex <- sapply(as.character(train$Sex), switch, 'male' = 0, 'female' = 1)
test$Sex <- sapply(as.character(test$Sex), switch, 'male' = 0, 'female' = 1)

# Change Embarked column to 0 = 'C', 1 = 'Q', 2 = 'S' and remove NAs
train$Embarked[train$Embarked == ''] <- 'S'
train$Embarked <- sapply(as.character(train$Embarked), switch, 'C' = 0, 'Q' = 1, 'S' = 2)
test$Embarked <- sapply(as.character(test$Embarked), switch, 'C' = 0, 'Q' = 1, 'S' = 2)

# Remove NAs from Age and Fare columns
train$Age[is.na(train$Age)] <- mean(train$Age,na.rm=T)
train$Fare[is.na(train$Fare)] <- mean(train$Fare,na.rm=T)
test$Age[is.na(test$Age)] <- mean(test$Age,na.rm=T)
test$Fare[is.na(test$Fare)] <- mean(test$Fare,na.rm=T)
```

## Arbori de decizie
```{r}
model <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + Title + Fsize,
                      data = train, method = "class", 
                      control=rpart.control(minsplit=124, cp=0.0078, maxcompete=113))

predict <- predict(object = model, newdata = train, type = "class")
fancyRpartPlot(model)

confusionMatrix(predict, as.factor(train$Survived))

prediction <- predict(model, newdata = test, type = "class")
solution <- data.frame(PassengerId = test$PassengerId, Survived = prediction)
write.csv(solution, file="../tema3/solutions/decision_tree_solution33.csv", row.names = FALSE)

accuracies <- c()
recalls <- c()
precissions <- c()
folds <- createFolds(train$Survived, k = 5, list = TRUE, returnTrain = TRUE)
for (i in 1:5) {
  model <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + Title + Fsize, 
                 data = train[folds[[i]],], method = "class", 
                 control=rpart.control(minsplit=124, cp=0.0078, maxcompete=113))
  prediction <- predict(object = model, newdata = train[-folds[[i]],], type = "class")
  accuracies <- c(accuracies, confusionMatrix(prediction, as.factor(train[-folds[[i]], ]$Survived))$overall[[1]])
  cm = as.matrix(table(prediction, train[-folds[[i]], ]$Survived))
  precissions <- c(precissions, cm[2,2] / sum(cm[,2]))
  recalls <- c(recalls, cm[2,2] / sum(cm[2,]))
}

paste("Accuracy: ", mean(accuracies))
paste("Precission: ", mean(precissions))
paste("Recall: ", mean(recalls))
```


## Bayes naiv
```{r}
model <- naiveBayes(as.factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
                    data=train,
                    method="class")

predict <- suppressWarnings(predict(object = model, newdata = train, type = "class"))
confusionMatrix(predict, as.factor(train$Survived))

prediction <- suppressWarnings(predict(model, newdata = test, type = "class"))
solution <- data.frame(PassengerId = test$PassengerId, Survived = prediction)
write.csv(solution, file="../tema3/solutions/naive_bayes_solution.csv", row.names = FALSE)

accuracies <- c()
recalls <- c()
precissions <- c()
folds <- createFolds(train$Survived, k = 5, list = TRUE, returnTrain = TRUE)
for (i in 1:5) {
  model <- naiveBayes(as.factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
                      data=train[folds[[i]],],
                      method="class")
  prediction <- suppressWarnings(predict(object = model, newdata = train[-folds[[i]],], type = "class"))
  accuracies <- c(accuracies, confusionMatrix(prediction, as.factor(train[-folds[[i]], ]$Survived))$overall[[1]])
  cm = as.matrix(table(prediction, train[-folds[[i]], ]$Survived))
  precissions <- c(precissions, cm[2,2] / sum(cm[,2]))
  recalls <- c(recalls, cm[2,2] / sum(cm[2,]))
}

paste("Accuracy: ", mean(accuracies))
paste("Precission: ", mean(precissions))
paste("Recall: ", mean(recalls))
```

## KNN
```{r}
prediction <- knn(train[,-c(1,2,10,11)], train[,-c(1,2,10,11)], train$Survived, k = 10,  l = 0, prob = FALSE, use.all = TRUE)
confusionMatrix(predict, as.factor(train$Survived))

prediction <- knn(train[,-c(1,2,10,11)], test[,-c(1,9,10)], train$Survived, k = 10,  l = 0, prob = FALSE, use.all = TRUE)
solution <- data.frame(PassengerId = test$PassengerId, Survived = prediction)
write.csv(solution, file="../tema3/solutions/knn_solution.csv", row.names = FALSE)

accuracies <- c()
recalls <- c()
precissions <- c()
folds <- createFolds(train$Survived, k = 10, list = TRUE, returnTrain = TRUE)
for (i in 1:5) {
  prediction <- knn(train[folds[[i]],-c(1,2,10,11)], train[-folds[[i]],-c(1,2,10,11)], train[folds[[i]],]$Survived, k = 5,  l = 0, prob = FALSE, use.all = TRUE)
  accuracies <- c(accuracies, confusionMatrix(prediction, as.factor(train[-folds[[i]],]$Survived))$overall[[1]])
  cm = as.matrix(table(prediction, train[-folds[[i]],]$Survived))
  precissions <- c(precissions, cm[2,2] / sum(cm[,2]))
  recalls <- c(recalls, cm[2,2] / sum(cm[2,]))
}

paste("Accuracy: ", mean(accuracies))
paste("Precission: ", mean(precissions))
paste("Recall: ", mean(recalls))
```

## Random forest
```{r}
model <- randomForest(as.factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
                              data=train, 
                              ntree=500)
model

predict <- predict(object = model, newdata = train, type = "class")
confusionMatrix(predict, as.factor(train$Survived))

prediction <- predict(model, newdata = test, type = "class")
solution <- data.frame(PassengerId = test$PassengerId, Survived = prediction)
write.csv(solution, file="../tema3/solutions/random_forest_solution.csv", row.names = FALSE)

accuracies <- c()
recalls <- c()
precissions <- c()
folds <- createFolds(as.factor(train$Survived), k = 5, list = TRUE, returnTrain = TRUE)
for (i in 1:5) {
  model <- randomForest(as.factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
                        data=train[folds[[i]],], 
                        ntree=500)
  
  prediction <- predict(object = model, newdata = train[-folds[[i]],], type = "class")
  accuracies <- c(accuracies, confusionMatrix(prediction, as.factor(train[-folds[[i]], ]$Survived))$overall[[1]])
  cm = as.matrix(table(prediction, train[-folds[[i]], ]$Survived))
  precissions <- c(precissions, cm[2,2] / sum(cm[,2]))
  recalls <- c(recalls, cm[2,2] / sum(cm[2,]))
}

paste("Accuracy: ", mean(accuracies))
paste("Precission: ", mean(precissions))
paste("Recall: ", mean(recalls))
```

## xgBoost
```{r}
dtrain <- xgb.DMatrix(data =  as.matrix(train[,-c(1,2,10,11)]), label = train$Survived)
dtest <- xgb.DMatrix(data =  as.matrix(test[,-c(1,9,10)]))
model <- xgboost(data = dtrain, max.depth = 10, eta=0.2, nthread = 2, nround = 2, objective = "binary:logistic")

predict <- predict(object = model, newdata = dtrain, type = "class")
predict <- as.numeric(predict > 0.5)
confusionMatrix(as.factor(predict), as.factor(train$Survived))

prediction <- predict(boost, newdata = dtest,  type = "class")
prediction <- as.numeric(prediction > 0.5)
solution <- data.frame(PassengerId = test$PassengerId, Survived = prediction)
write.csv(solution, file="../tema3/solutions/boost_solution.csv", row.names = FALSE)

dtrain <- xgb.DMatrix(data =  as.matrix(train[,-c(1,2,10,11)]), label = train$Survived)
model <- xgboost(data = dtrain, max.depth = 10, eta=0.2, nthread = 2, nround = 2, objective = "binary:logistic")

predict <- predict(object = model, newdata = dtrain, type = "class")
predict <- as.numeric(predict > 0.5)
confusionMatrix(as.factor(predict), as.factor(train$Survived))

accuracies <- c()
recalls <- c()
precissions <- c()
folds <- createFolds(train$Survived, k = 5, list = TRUE, returnTrain = TRUE)
for (i in 1:5) {
  dtrain <- xgb.DMatrix(data =  as.matrix(train[folds[[i]],-c(1,2,10,11)]), label = train[folds[[i]],]$Survived)
  dtest <- xgb.DMatrix(data =  as.matrix(train[-folds[[i]],-c(1,2,10,11)]), label = train[-folds[[i]],]$Survived)
  model <- xgboost(data = dtrain, max.depth = 10, eta=0.2, nthread = 2, nround = 5, objective = "binary:logistic")
  
  prediction <- predict(object = model, newdata = dtest, type = "class")
  prediction <- as.numeric(prediction > 0.5)
  accuracies <- c(accuracies, confusionMatrix(as.factor(prediction), as.factor(train[-folds[[i]], ]$Survived))$overall[[1]])
  cm = as.matrix(table(prediction, train[-folds[[i]], ]$Survived))
  precissions <- c(precissions, cm[2,2] / sum(cm[,2]))
  recalls <- c(recalls, cm[2,2] / sum(cm[2,]))
}

paste("Accuracy: ", mean(accuracies))
paste("Precission: ", mean(precissions))
paste("Recall: ", mean(recalls))
```

## Neural network
```{r}
model <- model.matrix(~ Survived + Pclass + Sex+ Age + Fare + SibSp, data = train)
model_test <- model.matrix(~ Pclass + Sex+ Age + Fare + SibSp, data = test)

neural_network <- neuralnet( 
  Survived ~ Pclass + Sex+ Age + Fare + SibSp, data=model, hidden=2, threshold=0.01, linear.output = F)
plot(neural_network)

predict <- neuralnet::compute(neural_network, model[,c("Pclass","Sex","Age", "Fare","SibSp")])
predict = round(predict$net.result)
confusionMatrix(as.factor(predict), as.factor(train$Survived))

prediction <- neuralnet::compute(neural_network, model_test[,c("Pclass","Sex","Age", "Fare","SibSp")])
prediction = round(prediction$net.result)
solution <- data.frame(PassengerId = test$PassengerId, Survived = prediction)
write.csv(solution, file="../tema3/solutions/nn_solution.csv", row.names = FALSE)

accuracies <- c()
recalls <- c()
precissions <- c()
folds <- createFolds(as.factor(train$Survived), k = 5, list = TRUE, returnTrain = TRUE)
for (i in 1:5) {
  model <- model.matrix(~ Survived + Pclass + Sex+ Age + Fare + SibSp, data = train[folds[[i]],])
  model_test <- model.matrix(~ Pclass + Sex+ Age + Fare + SibSp, data = train[-folds[[i]],])
  neural_network <- neuralnet( 
    Survived ~ Pclass + Sex+ Age + Fare + SibSp, data=model, hidden=2, threshold=0.01, linear.output = F)
  prediction <- neuralnet::compute(neural_network, model_test[,c("Pclass","Sex","Age", "Fare","SibSp")])
  prediction = round(prediction$net.result)
  
  accuracies <- c(accuracies, confusionMatrix(as.factor(prediction), as.factor(train[-folds[[i]], ]$Survived))$overall[[1]])
  cm = as.matrix(table(prediction, train[-folds[[i]], ]$Survived))
  precissions <- c(precissions, cm[2,2] / sum(cm[,2]))
  recalls <- c(recalls, cm[2,2] / sum(cm[2,]))
}

paste("Accuracy: ", mean(accuracies))
paste("Precission: ", mean(precissions))
paste("Recall: ", mean(recalls))
```

## SVM
```{r}
model <- svm(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
             data=train,
             cost=100,
             gamma=1)

predict <- predict(object = model, newdata = train, type = "class")
predict <- as.numeric(predict > 0.5)
confusionMatrix(as.factor(predict), as.factor(train$Survived))

prediction <- predict(svm, newdata = test)
prediction <- as.numeric(svm_prediction > 0.5)
solution <- data.frame(PassengerId = test$PassengerId, Survived = prediction)
write.csv(solution, file="../tema3/solutions/svm_solution.csv", row.names = FALSE)

accuracies <- c()
recalls <- c()
precissions <- c()
folds <- createFolds(as.factor(train$Survived), k = 5, list = TRUE, returnTrain = TRUE)
for (i in 1:5) {
  model <- svm(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
               data=train[folds[[i]],],
               cost=30,
               gamma=0.3)
  
  prediction <- predict(object = model, newdata = train[-folds[[i]],], type = "class")
  prediction <- as.numeric(prediction > 0.5)
  accuracies <- c(accuracies, confusionMatrix(as.factor(prediction), as.factor(train[-folds[[i]], ]$Survived))$overall[[1]])
  cm = as.matrix(table(prediction, train[-folds[[i]], ]$Survived))
  precissions <- c(precissions, cm[2,2] / sum(cm[,2]))
  recalls <- c(recalls, cm[2,2] / sum(cm[2,]))
}

paste("Accuracy: ", mean(accuracies))
paste("Precission: ", mean(precissions))
paste("Recall: ", mean(recalls))
```